occupation_1980 = {
    1: "Managerial specialty ope",
    2: "Prof specialty opr/tech",
    3: "Sales",
    4: "Clerical/admin supp",
    5: "Svc:prv hhld/clean/bldg",
    6: "Svc:protection",
    7: "Svc:food prep",
    8: "Health svc",
    9: "Personal svc",
    10: "Farming/forestry/fishing",
    11: "Mechanics/repair",
    12: "Constr trade/extractors",
    13: "Precision production",
    14: "Operators: machine",
    15: "Operators: transport, et",
    16: "Operators: handlers, etc",
    17: "Member of Armed Forces"
}

occupation_ahead = {
    1: "Professional/technical w",
    2: "Managers/officials/propr",
    3: "Clerical/kindred workers",
    4: "Sales workers",
    5: "Craftsmen/foremen/kindre",
    6: "Operatives/kindred worke",
    7: "Laborers/farm foremen",
    8: "Svc workers",
    9: "Farmers and farm manager"
}


occupation_2000 = {
    1: "Management Occupations",
    2: "Business Oper-ns Special",
    3: "Financial Specialists",
    4: "Computer+Math Occs",
    5: "Architecture+Engineering",
    6: "Life/Physical/SocialSci",
    7: "Community+Social Svcs Oc",
    8: "Legal Occups",
    9: "Education/Training/Libra",
    10: "Arts/Design/Entertnmt Oc",
    11: "Hlthcare Practition/Tech",
    12: "Healthcare Support Occs",
    13: "Protective Service Occs",
    14: "Food Prep+Serving Occs",
    15: "Blding/Grounds/Clean/Mai",
    16: "Personal Care+Service Oc",
    17: "Sales Occups",
    18: "Office+Admin Support Occ",
    19: "Farm/Fish/Forestry Occup",
    20: "Construction Trades",
    21: "Extraction Workers",
    22: "Install/Maint/Repair Wor",
    23: "Production Occups",
    24: "Transport/Material Movin",
    25: "Military Specific Occups"
}

occupation_2000 = {
    1: "Management Occupations",
    2: "Business Oper-ns Special",
    3: "Financial Specialists",
    4: "Computer+Math Occs",
    5: "Architecture+Engineering",
    6: "Life/Physical/SocialSci",
    7: "Community+Social Svcs Oc",
    8: "Legal Occups",
    9: "Education/Training/Libra",
    10: "Arts/Design/Entertnmt Oc",
    11: "Hlthcare Practition/Tech",
    12: "Healthcare Support Occs",
    13: "Protective Service Occs",
    14: "Food Prep+Serving Occs",
    15: "Blding/Grounds/Clean/Mai",
    16: "Personal Care+Service Oc",
    17: "Sales Occups",
    18: "Office+Admin Support Occ",
    19: "Farm/Fish/Forestry Occup",
    20: "Construction Trades",
    21: "Extraction Workers",
    22: "Install/Maint/Repair Wor",
    23: "Production Occups",
    24: "Transport/Material Movin",
    25: "Military Specific Occups"
}

occupation_2010 = {
    1: "Management Occs",
    2: "Business+Financial Oper-",
    3: "Computer+Mathematical Oc",
    4: "Architecture+Engineering",
    5: "Life/Physical/SocialSci",
    6: "Community+Social Service",
    7: "Legal Occs",
    8: "Education/Training/Libra",
    9: "Arts/Design/Entertainmen",
    10: "Healthcare Practitioners",
    11: "Healthcare Support Occs",
    12: "Protective Service Occs",
    13: "Food Prep+Serving Relate",
    14: "Building/Grounds Cleanin",
    15: "Personal Care+Service Oc",
    16: "Sales+Related Occs",
    17: "Office+Administrative Su",
    18: "Farming/Fishing/Forestry",
    19: "Construction+Extraction",
    20: "Installation/Maintenance",
    21: "Production Occs",
    22: "Transportation+Material",
    23: "Military Specific Occs"
}

# Standardized occupation groups across different census years
codeToGroup = {
    'Managerial specialty ope':'Management/Clerical/Business',
    'Clerical/admin supp':'Management/Clerical/Business',
    'Managers/officials/propr':'Management/Clerical/Business',
    'Clerical/kindred workers':'Management/Clerical/Business',
    'Management Occupations':'Management/Clerical/Business',
    'Business Oper-ns Special':'Management/Clerical/Business',
    'Financial Specialists':'Management/Clerical/Business',
    'Office+Admin Support Occ':'Management/Clerical/Business',
    'Management Occs':'Management/Clerical/Business',
    'Business+Financial Oper-':'Management/Clerical/Business',
    'Office+Administrative Su':'Management/Clerical/Business',
    'Sales':'Sales',
    'Sales workers':'Sales',
    'Sales Occups':'Sales',
    'Sales+Related Occs':'Sales',
    'Health svc':'Healthcare',
    'Hlthcare Practition/Tech':'Healthcare',
    'Healthcare Support Occs':'Healthcare',
    'Healthcare Practitioners':'Healthcare',
    'Svc:protection':'High Risk Occupations',
    'Member of Armed Forces':'High Risk Occupations',
    'Protective Service Occs':'High Risk Occupations',
    'Military Specific Occups':'High Risk Occupations',
    'Military Specific Occs':'High Risk Occupations',
    'Svc:prv hhld/clean/bldg':'Food/Personal/Service',
    'Svc:food prep':'Food/Personal/Service',
    'Personal svc':'Food/Personal/Service',
    'Svc workers':'Food/Personal/Service',
    'Food Prep+Serving Occs':'Food/Personal/Service',
    'Blding/Grounds/Clean/Mai':'Food/Personal/Service',
    'Personal Care+Service Oc':'Food/Personal/Service',
    'Food Prep+Serving Relate':'Food/Personal/Service',
    'Building/Grounds Cleanin':'Food/Personal/Service',
    'Farming/forestry/fishing':'Farming/Forestry/Fishing',
    'Farmers and farm manager':'Farming/Forestry/Fishing',
    'Farm/Fish/Forestry Occup':'Farming/Forestry/Fishing',
    'Farming/Fishing/Forestry':'Farming/Forestry/Fishing',
    'Mechanics/repair':'Skilled Trades/Production/Manual',
    'Constr trade/extractors':'Skilled Trades/Production/Manual',
    'Precision production':'Skilled Trades/Production/Manual',
    'Operators: machine':'Skilled Trades/Production/Manual',
    'Operators: transport, et':'Skilled Trades/Production/Manual',
    'Operators: handlers, etc':'Skilled Trades/Production/Manual',
    'Craftsmen/foremen/kindre':'Skilled Trades/Production/Manual',
    'Operatives/kindred worke':'Skilled Trades/Production/Manual',
    'Laborers/farm foremen':'Skilled Trades/Production/Manual',
    'Construction Trades':'Skilled Trades/Production/Manual',
    'Extraction Workers':'Skilled Trades/Production/Manual',
    'Install/Maint/Repair Wor':'Skilled Trades/Production/Manual',
    'Production Occups':'Skilled Trades/Production/Manual',
    'Transport/Material Movin':'Skilled Trades/Production/Manual',
    'Construction+Extraction':'Skilled Trades/Production/Manual',
    'Installation/Maintenance':'Skilled Trades/Production/Manual',
    'Production Occs':'Skilled Trades/Production/Manual',
    'Transportation+Material':'Skilled Trades/Production/Manual',
    'Prof specialty opr/tech':'STEM/Professional/Technical',
    'Professional/technical w':'STEM/Professional/Technical',
    'Computer+Math Occs':'STEM/Professional/Technical',
    'Architecture+Engineering':'STEM/Professional/Technical',
    'Life/Physical/SocialSci':'STEM/Professional/Technical',
    'Community+Social Svcs Oc':'STEM/Professional/Technical',
    'Legal Occups':'STEM/Professional/Technical',
    'Education/Training/Libra':'STEM/Professional/Technical',
    'Arts/Design/Entertnmt Oc':'STEM/Professional/Technical',
    'Computer+Mathematical Oc':'STEM/Professional/Technical',
    'Community+Social Service':'STEM/Professional/Technical',
    'Legal Occs':'STEM/Professional/Technical',
    'Arts/Design/Entertainmen':'STEM/Professional/Technical'
}
